### ISSUE TITLE
Move the Daemon Reload task to refactor

### ISSUE THREAD

**Issue by Enoal-Fauchille-Bolle** [Enoal-Fauchille-Bolle/Octopus#3]
**Description**  
Move the `daemon_reload` task into the `systemd` one to save time and simplify the role
The `systemd` module is made to include a `daemon_reload` parameter
```yaml
- name: Reload Systemd
  systemd:
    daemon_reload: yes

- name: Enable and start the application
  systemd:
    name: poll
    enabled: yes
    state: started
```

**Objectives**  
- Remove the `daemon_reload` task
- Make the `systemd` task include the `daemon_reload` parameter

**Acceptance Criteria**  
- Both the tasks are now merged
- The role is still working the same way
